### ISSUE TITLE
 Error: Attempting to run transaction which calls a contract function, but recipient address is not a contract address

### ISSUE THREAD

**Issue by thegostep** [LimeChain/etherlime#187]
Hi, I am getting this error when running etherlime tests on ganache:

```
     Error: Attempting to run transaction which calls a contract function, but recipient address 0xc9707E1e496C12f1Fa83AFbbA8735DA697cdBf64 is not a contract address
      at getResult (node_modules/etherlime/node_modules/ethers/providers/json-rpc-provider.js:40:21)
      at exports.XMLHttpRequest.request.onreadystatechange (node_modules/etherlime/node_modules/ethers/utils/web.js:111:30)
      at exports.XMLHttpRequest.dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at IncomingMessage.EventEmitter.emit (domain.js:441:20)
      at endReadableNT (_stream_readable.js:1129:12)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

It occurs on a simple call to a getter:
`let dataHash = await contract.getDataHash(user.address, prevHash, data);`

Which has been initiated as such:
```
deployer = new etherlime.EtherlimeGanacheDeployer(user.privateKey);
contract = await deployer.deploy(Contract);
```

**Comment by thegostep** [comment]
Found the issue. Contract inherited from an interface with an unimplemented function and therefore was deployed as abstract and without bytecode.
