### ISSUE TITLE
utils.timeTravel() in tests causes ganache instance to crash

### ISSUE THREAD

**Issue by thegostep** [LimeChain/etherlime#188]
Javascript invocation:
`await utils.timeTravel(deployer.provider, ethers.utils.bigNumberify('86400'));`

Surprisingly, setTimeTo() works as expected:
`await utils.setTimeTo(deployer.provider, ethers.utils.bigNumberify((await deployer.provider.getBlock("latest")).timestamp).add('86400'));`

Full ganache error message:

```
/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
^
Error: Number can only safely store up to 53 bits
    at r (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/bn.js/lib/bn.js:6:1)
    at n.assert [as toNumber] (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/bn.
js/lib/bn.js:506:1)
    at Object.toNumber [as bufferToInt] (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_m
odules/ethereumjs-util/dist/index.js:196:1)
    at Object.bufferToInt [as number] (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/util
s/to.js:84:1)
    at number (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/statemanager.js:522:1)
    at callback (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/blockchain_double.js:163:1
)
    at done (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/database/blockserializer.js:33
:1)
    at apply (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/async/dist/async.js:
473:1)
    at callback (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/async/dist/async.
js:1006:1)
    at replenish (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/async/dist/async
.js:1016:1)
    at _eachOfLimit (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/async/dist/as
ync.js:3196:1)
    at Object.fn (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/async/dist/async
.js:1046:1)
    at Object.eachSeries [as decode] (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/datab
ase/blockserializer.js:24:1)
    at decode (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/database/leveluparrayadapter
.js:33:1)
    at cb (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/level-sublevel/shell.js
:102:1)
    at cb (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/level-sublevel/nut.js:1
22:1)
    at callback (/Users/thegostep/github/erasure-quant-contracts/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/node_modules/cachedown/index.j
s:53:1)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

**Comment by NikolayAngelov** [comment]
Hey @thegostep.

Have you tried passing a normal number to the `timeTravel()`?

```wait utils.timeTravel(deployer.provider, 86400);```

**Comment by thegostep** [comment]
Yes ! This did the trick. Is it because ganache uses BN.js and is not compatible with BigNumber.js ?
