### ISSUE TITLE
Etherlime Ganache: Resource not found

### ISSUE THREAD

**Issue by javaadpatel** [LimeChain/etherlime#273]
Hi,
I've been running etherlime ganache command successfully but now when i try i get this error:

```
C:\Users\Javaad>etherlime ganache
[0] Address: 0xd9995bae12fee327256ffec1e3184d492bd94c31 Private key: 0x7ab741b57e8d94dd7e1a29055646bafde7010f38a900f55bbd7647880faa6ee8
[1] Address: 0xd4fa489eacc52ba59438993f37be9fcc20090e39 Private key: 0x2030b463177db2da82908ef90fa55ddfcef56e8183caf60db464bc398e736e6f
[2] Address: 0x760bf27cd45036a6c486802d30b5d90cffbe31fe Private key: 0x62ecd49c4ccb41a70ad46532aed63cf815de15864bc415c87d507afd6a5e8da2
[3] Address: 0x56a32fff5e5a8b40d6a21538579fb8922df5258c Private key: 0xf473040b1a83739a9c7cc1f5719fab0f5bf178f83314d98557c58aae1910e03a
[4] Address: 0xfec44e15328b7d1d8885a8226b0858964358f1d6 Private key: 0x823d590ed2cb5e8493bb0efc834771c1cde36f9fc49b9fe3620ebd0754ad6ea2
[5] Address: 0xda8a06f1c910cab18ad187be1faa2b8606c2ec86 Private key: 0xd6d710943471e4c37ceb787857e7a2b41ca57f9cb4307ee9a9b21436a8e709c3
[6] Address: 0x8199de05654e9afa5c081bce38f140082c9a7733 Private key: 0x187bb12e927c1652377405f81d93ce948a593f7d66cfba383ee761858b05921a
[7] Address: 0x28bf45680ca598708e5cdacc1414fcac04a3f1ed Private key: 0xf41486fdb04505e7966c8720a353ed92ce0d6830f8a5e915fbde735106a06d25
[8] Address: 0xf0508f89e26bd6b00f66a9d467678c7ed16a3c5a Private key: 0x6ca40ba4cca775643398385022264c0c414da1abd21d08d9e7136796a520a543
[9] Address: 0x87e0ed760fb316eeb94bd9cf23d1d2be87ace3d8 Private key: 0xfac0bc9325ad342033afe956e83f0bf8f1e863c1c3e956bc75d66961fe4cd186

Listening on http://localhost:8545
{ Error: Resource not found.
    at C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\keen-tracking\dist\node\webpack:\lib\utils\nodeRequestRetry.js:43:17
    at new Promise (<anonymous>)
    at parseBody (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\keen-tracking\dist\node\webpack:\lib\utils\nodeRequestRetry.js:31:12)
    at IncomingMessage.parseBody (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\keen-tracking\dist\node\webpack:\lib\utils\nodeRequestRetry.js:60:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ResourceNotFoundError' }
{ Error: Resource not found.
    at C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\keen-tracking\dist\node\webpack:\lib\utils\nodeRequestRetry.js:43:17
    at new Promise (<anonymous>)
    at parseBody (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\keen-tracking\dist\node\webpack:\lib\utils\nodeRequestRetry.js:31:12)
    at IncomingMessage.parseBody (C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\keen-tracking\dist\node\webpack:\lib\utils\nodeRequestRetry.js:60:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ResourceNotFoundError' }

C:\Users\Javaad\AppData\Roaming\npm\node_modules\etherlime\node_modules\solc\soljson.js:30
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__I_000101=Module["__GLOBAL__I_000101"]=asm["__GLOBAL__I_000101"];var __GLOBAL__sub_I_ABIFunctions_cpp=Module["__GLOBAL__sub_I_ABIFunctions_cpp"]=asm["__GLOBAL__sub_I_ABIFunctions_cpp"];var __GLOBAL__sub_I_ABI_cpp=Module["__GLOBAL__sub_I_ABI_cpp"]=asm["__GLOBAL__sub_I_ABI_cpp"];var __GLOBAL__sub_I_ASTJsonConverter_cpp=Module["__GLOBAL__sub_I_ASTJsonConverter_cpp"]=asm["__GLOBAL__sub_I_ASTJsonConverter_cpp"];var __GLOBAL__sub_I_AST_cpp=Module["__GLOBAL__sub_I_AST_cpp"]=asm["__GLOBAL__sub_I_AST_cpp"];var __GLOBAL__sub_I_ArrayUtils_cpp=Module["__GLOBAL__sub_I_ArrayUtils_cpp"]=asm["__GLOBAL__sub_I_ArrayUtils_cpp"];var __GLOBAL__sub_I_AsmAnalysis_cpp=Module["__GLOBAL__sub_I_AsmAnalysis_cpp"]=asm["__GLOBAL__sub_I_AsmAnalysis_cpp"];var __GLOBAL__sub_I_CompilerContext_cpp=Module["__GLOBAL__sub_I_CompilerContext_cpp"]=asm["__GLOBAL__sub_I_CompilerContext_cpp"];var _
abort({"code":"ResourceNotFoundError"}). Build with -s ASSERTIONS=1 for more info.
```

has anyone encountered this before?

**Comment by javaadpatel** [comment]
required an update to etherlime, resolved after updating.
