### ISSUE TITLE
etherlime flatten => TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by elenadimitrova** [LimeChain/etherlime#302]
This fails on all 3 contracts I tried from the [argent-contracts](https://github.com/argentlabs/argent-contracts) repo including simplified examples of having one import or no imports.

```
$ /Users/Elena/Source/argent-contracts/node_modules/.bin/etherlime flatten ens/ArgentENSManager.sol
TypeError: Cannot read property '0' of null
    at getSolcVersion (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:136:24)
    at createFolderAndFile (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:125:24)
    at recordFiles (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:97:2)
    at Object.run (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:24:2)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
✨  Done in 1.28s.
Galaxy-2:argent-contracts Elena$ yarn run etherlime flatten base/Managed.sol
yarn run v1.21.1
$ /Users/Elena/Source/argent-contracts/node_modules/.bin/etherlime flatten base/Managed.sol
TypeError: Cannot read property '0' of null
    at getSolcVersion (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:136:24)
    at createFolderAndFile (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:125:24)
    at recordFiles (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:97:2)
    at Object.run (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:24:2)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
✨  Done in 1.10s.
$ /Users/Elena/Source/argent-contracts/node_modules/.bin/etherlime flatten base/Owned.sol
TypeError: Cannot read property '0' of null
    at getSolcVersion (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:136:24)
    at createFolderAndFile (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:125:24)
    at recordFiles (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:97:2)
    at Object.run (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/flattener/flatten.js:24:2)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
✨  Done in 1.25s.
```

**Comment by ochikov** [comment]
Thank you for your issue. We are going to investigate.

**Comment by ochikov** [comment]
@elenadimitrova I found where the issue is coming from and I will do my best to release a fix soon! Thank you.

**Comment by ochikov** [comment]
@elenadimitrova Could you try to install etherlime 2.2.6 and try the flatten command ?

**Comment by elenadimitrova** [comment]
Yep that works, thanks.
