### ISSUE TITLE
solidity-coverage fixed to version 0.7.2

### ISSUE THREAD

**Issue by elenadimitrova** [LimeChain/etherlime#326]
`solidity-coverage` is pinned to specific version, currently 0.7.2. However the latest version is 0.7.4 which includes some fixes for the support of Solidity 0.6. There are likely to be more upcoming minor fixes and I can't see a reason to not allow it to upgrade it with something like `"solidity-coverage": "^0.7.2"`

Currently with the upgraded repo for argent-contracts we get the following error which _might_ be fixed in 0.7.4 

```
Error: Error: Could not instrument: modules/GuardianManager.sol. (Please verify solc can compile this file without errors.) Unrecognized expression
    at Object.runCoverage (/Users/Elena/Source/argent-contracts/node_modules/etherlime/cli-commands/etherlime-test/etherlime-coverage.js:84:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at findNodeScript.then.existing (/Users/Elena/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
etherlime coverage [path] [timeout] [port] [solcVersion] [workingDirectory]
[html] [ignoreFiles]
```

**Comment by ochikov** [comment]
Thank you. I will fix it.
