### ISSUE TITLE
etherlime ganache gives error

### ISSUE THREAD

**Issue by mudgen** [LimeChain/etherlime#330]
When I run `etherlime ganache` I get this error:

```
Error: Callback was already called.
    at C:\Users\mudge\AppData\Roaming\npm\node_modules\etherlime\node_modules\ganache-cli\build\ganache-core.node.cli.js:17:276
    at s.<anonymous> (C:\Users\mudge\AppData\Roaming\npm\node_modules\etherlime\node_modules\ganache-cli\build\ganache-core.node.cli.js:17:2238)
    at s.emit (events.js:314:20)
    at s.destroy (C:\Users\mudge\AppData\Roaming\npm\node_modules\etherlime\node_modules\ganache-cli\build\ganache-core.node.cli.js:37:712589)
    at finish (_stream_writable.js:658:14)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I think I may be getting this error because I am using Node version v14.5.0.   I need this to work using v14.5.0.

I am using etherlime version 2.3.2.

**Comment by ochikov** [comment]
Etherlime `2.3.5` now supports node v14.
